structuring_prompt: |
  "You are an expert in structuring content. Your task is to analyze the following unstructured text chunk and organize it into a clear, coherent, and structured format. Focus on identifying the main topics, key points, and any hierarchical relationships in the text. Present the output in a clean and readable format, using Markdown for structure. Do not add any new information, only structure the existing content."

  Unstructured Text:
  """
  {text_chunk}
  """

  Structured Content:

qa_generation_prompt: |
  "You are an expert in generating high-quality question-answer pairs for fine-tuning LLMs. Your task is to create a set of 5-10 diverse and informative question-answer pairs from the following structured text. The questions should cover different aspects of the text, including factual recall, summarization, and reasoning. The answers should be concise and directly extracted from the provided text."

  Structured Text:
  """
  {structured_chunk}
  """

  Generate the Q&A pairs in the following JSONL format, with each pair on a new line. Only output the JSONL content, with no other text or explanations.
  {{"question": "...", "answer": "..."}}
  {{"question": "...", "answer": "..."}}